# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bcfe920452b11ce54f51a9bb35fbe649e56e46188b5ea0d3a7c0ccc38d84474604997dcac69e827ce038930e8a777133ca0427da7aa7d5e19be57dc91dcaec9

test:
  secret_key_base: 9d6855524414b8e8e0a7eb2debb97e58587a7d2bc8d67119fd03865bee02f25a1000e03f7c184c962abd91b0a67b71dacad4eeaf23aa7d022ffd028ad9be7cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
